language: shell
os:
    - linux
    - osx
    - windows

before_install:
    - export PATH="$HOME/miniconda3/bin:$PATH"
    # give execution permissions to travis/install_conda.sh
    #- chmod +x travis/install_conda.sh

install:
    # install conda with custom script
    - bash travis/install_conda.sh

    # create and activate conda environment
    - conda env create --file environment.yaml
    - source activate pycalculator_env

script:
    - python -m unittest discover -v test
    - cd doc
    - make doctest
    - make html
