language: shell
os:
    - linux
    - osx
    - windows

install:
    # install conda with custom script
    - bash travis/install_conda.sh
    - export PATH="$HOME/miniconda3/bin:$PATH"

    # create and activate conda environment
    - conda env create --file environment.yaml
    - source activate pycalculator_env

script:
    - python -m unittest discover -v test
    - cd doc
    - make doctest
    - make html
