language: shell
os:
    - linux
    - osx
    #- windows

before_install:
    # set miniconda3 path on macOS and Linux
    - export PATH="$HOME/miniconda3/bin:$PATH"

install:
    # install conda with custom script
    - bash travis/install_conda.sh

    # create and activate conda environment
    - ls
    - conda env create --file environment.yml
    - source activate pycalculator_env

script:
    # run unit test
    - python -m unittest discover -v test

    # run doctest and sphinx documentation build
    - cd doc
    - make doctest
    - make html
